### ISSUE TITLE
Find query with more than 1 condition

### ISSUE THREAD

**Issue by arnoldtonderaimarunda** [solso/jor#3]
`jor.devices.find({"id" => 10, "user" => "Joe Bloggs" })`

The above instruction is not returning any records. 

However, `jor.devices.find({"id" => 10 })` or `jor.devices.find({"user" => "Joe Bloggs" })` returns records based on since condition.

How do I perform a **Find** query with more than one condition?

**Comment by solso** [comment]
Multiple conditions are not supported on the library itself.

Of course, you can always do the AND, OR, etc. at the "application level"
with the n result-sets of single term conditions, basically, you have to
write it yourself, sorry for the trouble.

At the time I did not find a way to leverage the speed of Redis to support
arbitrary conditions I decided to not offer them on the library, because it
would have been just a naive list of sequential finds. With lua scripting
in Redis, however, it would be possible to get a speed up, as the
individuals finds could be resolved in the Redis space, lua is faster than
ruby and you save in network IO. That would be a nice extra feature.

**Comment by arnoldtonderaimarunda** [comment]
Appreciate the explanation. JOR has really been useful to me, many thanks
